### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by AveryanAlex** [vikulin/ygg_me_nice_ipv6#6]
Please, publish release after merge [this](https://github.com/vikulin/ygg_me_nice_ipv6/pull/5). And, if you can, for linux too.

**Comment by vikulin** [comment]
You did a mistake here
https://github.com/vikulin/ygg_me_nice_ipv6/blob/master/src/ygg_nice_ipv6.go#L43

Should be
`
if len(os.Args) == 1 {
`
вс, 2 авг. 2020 г. в 18:17, Александр Аверьянов <notifications@github.com>:

**Comment by vikulin** [comment]
Done.

**Comment by AveryanAlex** [comment]
Yes, I know, but I already fixed it
